### ISSUE TITLE
Implémenter la date de parution d'une offre

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-api#22]
Ajouter le champ de la date de parution/publication

**Comment by zYmMiJ** [comment]
Mettre à jour la version du sdk a au moins 0.1.31 quand elle sera release

**Comment by adriens** [comment]
👍  Merci pour la qualité des commetaires, en remote c'est encore plus important. N'hésites pas à passer du temps à bien décrire, ce n'est pas du temps perdu.

**Comment by adriens** [comment]
👏
