### ISSUE TITLE
Vérifier les différences de données d'Employeurs

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-api#23]
- [X] Vérifier les différences entres les deux URL : 

https://emploi.gouv.nc/api/v1/offres/employeurs/public/findAllEmployeurWithCountOffres?page=0&size=100

https://emploi.gouv.nc/api/v1/offres/public/search?size=12&sort=datePublication,desc&motsCles=&priseDePosteDu=&priseDePosteAu=

- [X] Commenter le schéma de données sous ce ticket : 

- [X] Puis créer les ticket pour la mise à jour des routes.

**Comment by adriens** [comment]
je crois les doigts pour ce soient les mêmes entités 🤞

**Comment by zYmMiJ** [comment]
Comparaison des id pour les URL pour un même employeur : 

1. https://emploi.gouv.nc/api/v1/offres/public/search?size=1000&sort=datePublication,desc&motsCles=&priseDePosteDu=&priseDePosteAu=

Element 120/189 :

![image](https://user-images.githubusercontent.com/43323367/77364798-15270200-6da9-11ea-8c57-f519254b5296.png)

Element 121/189 :

![image](https://user-images.githubusercontent.com/43323367/77365073-92eb0d80-6da9-11ea-8acc-c118f45cfc4e.png)


2.https://emploi.gouv.nc/api/v1/offres/employeurs/public/findAllEmployeurWithCountOffres?page=0&size=100

Element 0/82:

![image](https://user-images.githubusercontent.com/43323367/77365239-dcd3f380-6da9-11ea-9015-4317463c6fcc.png)

Les id ne sont pas fiables pour faire le lien entre les différentes URL.

**Comment by adriens** [comment]
ok, ce sont des  `UUID` en fait, c'était à craindre.

**Comment by zYmMiJ** [comment]
Que faire ?

Ce qu'on à on a pour l'instant une liste d'offre d'emploi et l'employeur via l'url : 

https://emploi.gouv.nc/api/v1/offres/public/search?size=1000&sort=datePublication,desc&motsCles=&priseDePosteDu=&priseDePosteAu=

Faire le lien offre d'emploi/Employeurs via le nom entre les trois URL ?
https://emploi.gouv.nc/api/v1/offres/public/search?size=1000&sort=datePublication,desc&motsCles=&priseDePosteDu=&priseDePosteAu=
https://emploi.gouv.nc/api/v1/offres/employeurs/public/findAllEmployeurWithCountOffres?page=0&size=100
https://emploi.gouv.nc/api/v1/offres/public/search?page=0&size=12&sort=datePublication,desc&motsCles=%20Easy%20Skill%20

 => nécessite de supprimer les doublons, fastidieux

Ne pas faire le lien, avoir une liste (offre d'emploi et l'employeur) et une autre (Employeur offre d'emploi)  => doublons, interdis certaines action par exemple : consulter offre d'emploi > consulter employeur > consulter toutes les offres d'emplois de cet employeur

Ne posséder qu'une liste offre d'emploi et l'employeur, Employeur via l'url : 

https://emploi.gouv.nc/api/v1/offres/public/search?size=1000&sort=datePublication,desc&motsCles=&priseDePosteDu=&priseDePosteAu=

=> Nous ne pouvons avoir toutes les offres d'emploi d'un employeur

Reconstruire une structure donnée => nécessite de la stockée 

Autre ?

**Comment by adriens** [comment]
Première propositoin sur slack

**Comment by zYmMiJ** [comment]
Lorsque je clique sur un employeur, je récupère la liste de toutes ses offres via sa clé.

Choix adopté : 

- [X] Faire le lien offre d'emploi/Employeurs via le nom

**Comment by adriens** [comment]
Beau ticket très bien commenté, très belle étude

**Comment by zYmMiJ** [comment]
cf https://github.com/adriens/emploi-nc-sdk/commit/2ae6a68b1ad1eadd7a7e54e1bb6289646d4932ae

et pour la maj du ticket cf https://github.com/adriens/emploi-nc-api/issues/16
