### ISSUE TITLE
Changement endpoint /employeurs/{id en name}

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-api#24]
Changement du en endpoint /employeurs/{id} /employeurs/{name}

**Comment by adriens** [comment]
La route c dans l'appli, ici c des endpoints.

On est alignés ?

**Comment by zYmMiJ** [comment]
Oui c'est ca je modifie le ticket.

**Comment by zYmMiJ** [comment]
cf 8525d85c6b8539e958324af6d99be7eebc89b7e7
