### ISSUE TITLE
Mis à Jour rapidAPI

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-api#27]
Mettre à jour l'api rapid API de la release 0.1.13 (Latest)

Nouveau Endpoint : 

- [x] /employeurs 
renvoie la liste de tout les employeurs

- [x] /employeurs/{name} 
renvoie un employeur précis selon son nom exacte

- [x] /emploi/{numero} 
renvoie l'offre d'emploi selon son numéro emploi.gouv.nc

- [x] /emploi/{numero}/employeur
renvoie l'employeur d'une offre d'emploi précise

Mis à jour docs:

- [x] /emploi/latest/
revoie les 25 dernières offres

**Comment by adriens** [comment]
Mergé cf #28

**Comment by adriens** [comment]
# Status

- [x] API déployée
- [ ] Docs à finaliser pour les samples: besoin d'examples de variables

# Besoin de données supplémentaire

Il me manque des valeurs d'exemple pour préparer le sample dans la doc, pour :


- `/employeurs/{name}`
- `/emploi/{numero}`

**Comment by zYmMiJ** [comment]
/employeurs/MRT
/employeurs/IFINGO

/emploi/4480
/emploi/4518

**Comment by adriens** [comment]
C'est parti, je complète 👍

**Comment by adriens** [comment]
C fait ✔️
