### ISSUE TITLE
Implémenter le Endpoint search/{nombreMaxOffres}/{MotsClès}/{commune}/{contrat}/{dateDebut}/{dateFin}

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-api#30]
Route qui nous servira a implémenter la recherche avancées sur toutes les offres.
Reprends le modèle de emploi.gouv.nc

**Comment by adriens** [comment]
❔

**Comment by zYmMiJ** [comment]
ut du endpoint search/{nombreMaxOffres}/{MotsClès}/{commune}/{contrat}/{dateDebut}/{dateFin}

- nombreMaxOffres : nombres d'offres d'emplois maximum que renvoie le endpoint

- MotsClès : Même fonctionnement que celui de emploi.gouv.nc 

C'est-à-dire : recherche full texte sur tout les champs des offres (le métiers,lieu etc ... )

Si plusieurs mots clès les séparés par & .

- commune : nom de la commune par exemple Nouméa. Casse et accents importants se référer pour l'instant à https://emploi.gouv.nc/offres/recherche et la liste présente dans lieu.

- dateDebut/dateFin : Période de la prise de poste spécifiée l'offre d'emploi.

Encoder deux fois / : %252F : à corriger

**Important :**  si vous ne voulez pas rentrer un paramètre le remplacer par ``none`

- Endpoint : search/{nombreMaxOffres}/{MotsClès}/{commune}/{contrat}/{dateDebut}/{dateFin}

- Exemple : /search/30/none/Nouméa/CDI/none/none
/search/30/none/Nouméa/CDI/01%252F04%252F2020/08%252F04%252F2020

**Comment by zYmMiJ** [comment]
update du endpoint search/{nombreMaxOffres}/{MotsClès}/{commune}/{contrat}/{dateDebut}/{dateFin}

nombreMaxOffres : nombres d'offres d'emplois maximum que renvoie le endpoint

MotsClès : Même fonctionnement que celui de emploi.gouv.nc

C'est-à-dire : recherche full texte sur tout les champs des offres (le métiers,lieu etc ... )

Si plusieurs mots clès les séparés par &, par exemple (chef&projet).

commune : nom de la commune par exemple Nouméa. Casse et accents importants se référer pour l'instant à https://emploi.gouv.nc/offres/recherche et la liste présente dans lieu.

dateDebut/dateFin : Période de la prise de poste spécifiée l'offre d'emploi. Format ddmmyyyy.

**Important :** si vous ne voulez pas rentrer un paramètre le remplacer par `none`

Endpoint : search/{nombreMaxOffres}/{MotsClès}/{commune}/{contrat}/{dateDebut}/{dateFin}

Exemple : /search/30/none/Nouméa/CDI/none/none
/search/30/none/Nouméa/CDI/01%252F04%252F2020/08%252F04%252F2020
