### ISSUE TITLE
Mettre a jour API à la release 0.1.15 sur Heroku/RapidAPI

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-api#31]

**Comment by adriens** [comment]
Ca consiste juste à déployer ? Pas de maj de doc ? @zYmMiJ ❔

**Comment by adriens** [comment]
Il me faut un exemple pour le nouvel endpoint stp

**Comment by adriens** [comment]
C'est déployé ✔️

**Comment by adriens** [comment]
Pour la partie rapid API, faire un autre ticket stp avec 

- ajout endpoint
- doucmentation endpoint avec params d'exemple

**Comment by zYmMiJ** [comment]
cf https://github.com/adriens/emploi-nc-api/issues/30 

Attention bug : 

- cf https://github.com/adriens/emploi-nc-sdk/issues/15

- cf https://github.com/adriens/emploi-nc-api/issues/33

**Comment by adriens** [comment]
Oki, j'ai vu passer SDK et API, je mesuis dit oula y'a u ntruc 😆

**Comment by adriens** [comment]
tu me dis, pas de souci
je déploierai
