### ISSUE TITLE
Implémenter SPring Rest Docs

### ISSUE THREAD

**Issue by adriens** [adriens/emploi-nc-api#36]
voir https://spring.io/projects/spring-restdocs

cf #4

**Comment by adriens** [comment]
Déja implémenté ❔ ❔

**Comment by zYmMiJ** [comment]
Sur la release 0.1.17 je redirige vers la docs et le liens est-ce bien cela ?

**Comment by adriens** [comment]
Non, pas du tout, ça redirige vers une page qui décrit l'API embarquée

**Comment by adriens** [comment]
On fera ce ticket plus tard, c'est pas urgent

**Comment by zYmMiJ** [comment]
ok

**Comment by adriens** [comment]
Un bon tuto https://www.baeldung.com/spring-rest-docs

**Comment by zYmMiJ** [comment]
cf https://github.com/adriens/emploi-nc-api/issues/60
