### ISSUE TITLE
Export csv

### ISSUE THREAD

**Issue by zYmMiJ** [adriens/emploi-nc-api#48]
Création d'un endpoint qui rend un fichier csv qui permet de faire des stats sur les offres.

- [x] Choix des données qu'on rend 

- [x] Création du endpoint

**Comment by zYmMiJ** [comment]
cf https://github.com/adriens/emploi-nc-api/releases/tag/0.1.22

**Comment by adriens** [comment]
Hello @zYmMiJ , tu peux préciser le endpoint stp ? J'aimerais faire joujou un peu avec 😄

**Comment by zYmMiJ** [comment]
Salut, dsl j'étai pas de mon pc ajd le endpoint est le suivant : /csv .

**Comment by zYmMiJ** [comment]
Un lien de ce que j'ai fais sur google data studio : https://datastudio.google.com/reporting/b852a7b4-275e-4aef-a13c-ad9e4abca1ec .

**Comment by adriens** [comment]
Pour la date, au format YYYY/DD/DD, actuellement c'est `02/06/2020`

**Comment by adriens** [comment]
Je crois que ça serait super cool d'avoir l'url de l'annonce aussi, j'ai une idée 😄

**Comment by adriens** [comment]
du coup, la rajouter au SDK 🙏

**Comment by zYmMiJ** [comment]
cf https://github.com/adriens/emploi-nc-api/commit/7cba9307d60ae50d88658a98acce0c87c0bc1b3d

- [X] Ajout de l'url dans le fichier csv 

- [X]  Mise à jour fichier d'exemple

- [X] Déploiement auto lancé

- [ ] Déploiement reussi

**Comment by zYmMiJ** [comment]
Si besoin de remonter d'autres éléments/données faites le savoir sous ce ticket ou sur une nouvelle issue sinon ce ticket sera bientot fermé.

**Comment by adriens** [comment]
C'est top, on l'a testé hier, je ferme ça répond parfaitementa aux objectifs 👏
