### ISSUE TITLE
.csv - Modifications à apporter au fichier d'export /csv

### ISSUE THREAD

**Issue by HakumenNC** [adriens/emploi-nc-api#54]
Bonjour,

Pouvez-vous, s'il vous plaît apporter les modifications suivantes au fichier récupéré par l'endpoint `/csv` :

* Encodage : `utf-8`
* Séparateur de ligne : `LF`
* Mettre les valeurs de type `String` entre *double-quotes*

D'avance merci

**Comment by adriens** [comment]
Bien vu @HakumenNC 👍

**Comment by zYmMiJ** [comment]
J'ai ajouter un endpoint /excel qui permet d'ouvrir le fichier csv correctement selon l'encodage par defaut d'excel qui semble etre windows 1252.

Le endpoint /csv semble bien rendre du utf-8, en tout cas maintenant oui.

Pour le séparateur de ligne le /csv c'est du ``\r\n"` et le /excel ``\n`` j'ai garder par défaut les préférences que la librairie proposer c'est modifiable.

Pour lire correctement un fichier csv correctement depuis excel j'ai trouvé celle-ci :

![image](https://user-images.githubusercontent.com/43323367/84137392-5e2d4f00-aa98-11ea-96d8-58af794fa241.png)

Ouvrir le fichier généré par /csv

![image](https://user-images.githubusercontent.com/43323367/84137511-87e67600-aa98-11ea-82dd-42f029a12279.png)

Si la problématique de l'encodage ou/et du retour à la ligne persiste fait moi signe.

**Comment by adriens** [comment]
EH EH EH, y''en a qui jouent avec PBI...

**Comment by adriens** [comment]
Cool l'analyse @zYmMiJ , c du bon boulot !

**Comment by adriens** [comment]
Je vais jouer avec ❕ 💟 🚀
