### ISSUE TITLE
.csv - Ajout de l'information typeContrat

### ISSUE THREAD

**Issue by HakumenNC** [adriens/emploi-nc-api#55]
Bonjour,

Serait-il possible d'ajouter le champ `typeContrat` au fichier csv ?

```json
{ "typeContrat": "CDI" }
```
D'avance merci

**Comment by adriens** [comment]
Yes, bien vu, ça va être bien clivant ça ! 👏

**Comment by zYmMiJ** [comment]
@HakumenNC hésite pas a la re ouvrir si ya un problème

**Comment by adriens** [comment]
ca va envoyer du pâté les tableaux de bord, si vous continuez, on va se lancer un concours les gars, me cherchez pas !
